import { OnboardingStepConfig } from '../types';

export const ONBOARDING_STEPS: OnboardingStepConfig[] = [
  {
    id: 'display_name',
    title: 'What should we call you?',
    subtitle: "Enter the name you'd like to use across the platform.",
    shortLabel: 'Display Name',
    motivationalTitle: "Let's get started 👋",
    motivationalSubtitle: 'We need a few details to create your profile and personalize your workspace.',
    quote: 'Every breakthrough prompt begins with a clear voice.',
    badgeEmoji: '🚀',
  },
  {
    id: 'role',
    title: 'Select your primary role',
    subtitle: 'Choose the role that best describes your daily focus.',
    shortLabel: 'Role',
    motivationalTitle: "You're doing great! 🎉",
    motivationalSubtitle: 'Just a few more details to complete your account setup and tailor your experience.',
    quote: 'Specialized roles yield 10x more targeted, high-impact results.',
    badgeEmoji: '🔥',
  },
  {
    id: 'mode',
    title: 'Choose your primary mode',
    subtitle: 'Select a mode associated with your role to personalize your experience.',
    shortLabel: 'Mode',
    motivationalTitle: "You're on a roll! ⚡",
    motivationalSubtitle: 'Halfway there! Choose your default focus mode for instant prompt enhancement.',
    quote: 'The right mode transforms raw ideas into polished masterpieces.',
    badgeEmoji: '⚡',
  },
  {
    id: 'avatar',
    title: 'Customize your avatar',
    subtitle: 'Upload a photo or choose from our collection.',
    shortLabel: 'Avatar',
    isOptional: true,
    motivationalTitle: 'Looking awesome! ✨',
    motivationalSubtitle: 'Add your personal avatar to make your workspace feel like home.',
    quote: 'Put a face to your creative vision across every prompt.',
    badgeEmoji: '🌟',
  },
  {
    id: 'theme',
    title: 'Choose your default theme',
    subtitle: 'You can change the theme anytime in Settings.',
    shortLabel: 'Theme',
    motivationalTitle: 'Almost at the finish line! 🎯',
    motivationalSubtitle: 'Final stretch! Pick the workspace aesthetic that fuels your daily focus.',
    quote: 'Your creative space should inspire your best thinking.',
    badgeEmoji: '🏆',
  },
  {
    id: 'complete',
    title: "You're all set!",
    subtitle: 'Review your settings below and finish setup.',
    shortLabel: 'Review',
    motivationalTitle: "You're all set! 🎊",
    motivationalSubtitle: "Everything is ready. Let's start engineering extraordinary prompts.",
    quote: 'Welcome to AURE — where ideas become elite prompts.',
    badgeEmoji: '🎉',
  },
];

